### ISSUE TITLE
test package

### ISSUE THREAD

**Issue by cup** [cup/sage#34]
mingw gcc 7 is a test package - but cygwin gcc 7 is not

http://cygwin.com/ml/cygwin/2018-07/msg00168.html

https://github.com/cup/mauve/projects/3

**Comment by svnpenn** [comment]
https://github.com/svnpenn/glade/issues/12

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/35

**Comment by cup** [comment]
https://github.com/cup/glade/issues/4

**Comment by cup** [comment]
https://github.com/cup/glade/issues/15

**Comment by cup** [comment]
https://github.com/cup/glade/issues/6

**Comment by cup** [comment]
https://github.com/cup/glade/issues/14

**Comment by cup** [comment]
https://github.com/cup/sage/issues/21

**Comment by cup** [comment]
this issue is now invalid because of GCC 8 - we might need test package down the road

will reopen at that time
