### ISSUE TITLE
mkdir: cannot create directory ‘//x86_64’: Read-only file system

### ISSUE THREAD

**Issue by cup** [cup/sage#35]
~~~sh
$ rm -f /etc/setup/setup.sh
$ sage install curl
mkdir: cannot create directory ‘//x86_64’: Read-only file system
~~~

**Comment by svnpenn** [comment]
https://github.com/svnpenn/sage/issues/34

**Comment by svnpenn** [comment]
https://github.com/svnpenn/velour/issues/73

**Comment by cup** [comment]
https://github.com/cup/sage/issues/37

**Comment by cup** [comment]
closing this in favor of https://github.com/cup/sage/issues/21

**Comment by cup** [comment]
closing this in favor of https://github.com/cup/sage/issues/21
