### ISSUE TITLE
Script needs some external variables ($lastcache and $elastmirror)

### ISSUE THREAD

**Issue by Prince-Mandor** [cup/sage#38]
Using "sage update" cause it to fail, because this variables are empty

https://github.com/cup/sage/blob/858cf4e2b65e2f58c8f528c241a93dcc9a0967e5/sage.sh#L118

**Comment by cup** [comment]
working fine here - make sure you have Velour installed

http://github.com/cup/velour

**Comment by Prince-Mandor** [comment]
you try to say, $lastcache variable provided by Velour?   :)
Yes, I have Velour installed.

Can you please specify, where exactly this variables get some value assigned to them?
