### ISSUE TITLE
Setup Script fails if run from anywhere other than its original installed directory

### ISSUE THREAD

**Issue by cslycord** [cup/sage#40]
Inside setup.sh, every symlink is set relative to $PWD, which is the directory that one calls the script from, and not the directory in which setup.sh is located.

Running the script from anywhere other than the git root directory results in links to non-existent files.

**Comment by cslycord** [comment]
And a fix for it:

`#!/bin/dash -e
DIR=$(dirname $(realpath $0))
ln -f -s "$DIR"/extras/sage-cost.sh /usr/bin/sage-cost
ln -f -s "$DIR"/extras/sage-date.awk /usr/bin/sage-date
ln -f -s "$DIR"/extras/sage-prune.sh /usr/bin/sage-prune
ln -f -s "$DIR"/extras/sage-spy.awk /usr/bin/sage-spy
ln -f -s "$DIR"/sage.sh /usr/bin/sage

mkdir -p /usr/share/sage
ln -f -s "$DIR"/docs/data.yml /usr/share/sage`

**Comment by cup** [comment]
thank you - but i think your method fails if you source the script - EG `. setup.sh`

so i am hesitant to implement this unless its truly robust

i am closing for now - if you can prove your method handle these case i will reopen

thanks

**Comment by cslycord** [comment]
The following works both when sourced and not, as well as allowing for running the script from any directory.

`#!/bin/dash -e
DIR=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )
ln -f -s "$DIR"/extras/sage-cost.sh /usr/bin/sage-cost
ln -f -s "$DIR"/extras/sage-date.awk /usr/bin/sage-date
ln -f -s "$DIR"/extras/sage-prune.sh /usr/bin/sage-prune
ln -f -s "$DIR"/extras/sage-spy.awk /usr/bin/sage-spy
ln -f -s "$DIR"/sage.sh /usr/bin/sage

mkdir -p /usr/share/sage
ln -f -s "$DIR"/docs/data.yml /usr/share/sage`

**Comment by cup** [comment]
can you confirm this method works with standard input - for example

~~~
sh < setup.sh
~~~

i cant test right now - i would again like to stress that i think this is a bad
idea - see this link:

http://mywiki.wooledge.org/BashFAQ/028
